### ISSUE TITLE
Simplifique o seu CSS

### ISSUE THREAD

**Issue by justguerra** [renataquinaga/Meuprimeirosite#2]
Rê,

Existe a prática de manter o CSS o mais enxuto possível, ou seja [DRY CSS](https://vanseodesign.com/css/dry-principles/)(Don't Repeat Yourself). Segue uma sugestão de como poderia diminuir o seu CSS.

Original:
   

       h1 {
            font-family: 'Courier New', Courier, monospace;
            font-size: 200px;
        }
        
        h2 {
            font-family: 'Courier New', Courier, monospace;
            font-size: 50px;
        }
       
        h3 {
            font-family: 'Courier New', Courier, monospace;
            font-size: 30px;
        }

DRY CSS:
```

        h1, h2, h3, h4 {
            font-family: 'Courier New', Courier, monospace;
        }

        h1 {
            font-size: 200px;
        }
        h2 {
            font-size: 50px;
        }
       
        h3 {
            font-size: 30px;
        }
```

Abraços!

**Comment by renataquinaga** [comment]
Obrigada pela dica! :)

**Comment by justguerra** [comment]
# # #6138739acec54b0329b415d258c6e77e8e19fefe

**Comment by justguerra** [comment]
57bec3068e2702aaacb0a11be797f963f29b0262

**Comment by justguerra** [comment]
Modificado no 6138739acec54b0329b415d258c6e77e8e19fefe
