### ISSUE TITLE
Colocar o Max-Width nas IMGs

### ISSUE THREAD

**Issue by justguerra** [renataquinaga/Meuprimeirosite#3]
Rê, 

A Imagem da Camila é muito grande e acaba quebrando o seu layout em telas pequenas ou celulares. Veja o exemplo:

![image](https://user-images.githubusercontent.com/4557658/97808282-c3026500-1c44-11eb-96d4-3269c59b3be5.png)

Aconselho utilizar max-width ou fixar uma width em todos os sites.

Sem ser isso, o site está lindo!

Parabéns aluna prodígio! ;)

**Comment by renataquinaga** [comment]
Alteração realizada!

Mas... Não lembro como era a forma correta/ socialmente aceitável/ organizada de responder! Desculpa!
Adicionei esse código aqui:

body img {
            max-width: 80vw;
        }

commit: 8cd9dfdd0116ccc07bd87bc3c305255811549e7e

Era isso? haha

**Comment by justguerra** [comment]
Isso aí, boa!
